### ISSUE TITLE
Seesawfacenet

### ISSUE THREAD

**Issue by AnthonyF333** [cvtower/SeesawNet_pytorch#3]
Hello @cvtower, great work for seesawnet, but I prefer to know when the seesawfacenet will be released?

**Comment by cvtower** [comment]
Hi @tankrant , sorry for the delayed reply.  Seesawfacenet is my private work but my team would like to open source the mnn/ncnn version first by the team account.  Anyway, we have a meeting tomorrow about this issue and pytorch implement of seesawfacenet will be open-source by this week. Like this seesaw net repo, i will release all codes and pretrained models along with tfboard logs. I will @ you then.

**Comment by AnthonyF333** [comment]
Thank you very much! @cvtower
